# 
#Teaching a machine/computer/program to make decision making....
#if we increase the feature then the accuracy will decrease...

#output fixed/discrete hole classification...
#output continuous hole regression...

#Unsupervised Learing: If there is no target..
#Supervised Learing : If target is given...
#Suppervised er moddhe Classification and Regression...

#AI > ML > DL...

#Machine Learing : 
            #Image : 2D and 3D Computer Vision.
            #Text  :Natural Language Processing.
            #ECE Signal/ EEG Signal : Signal Processing .
            #